WITH TLE as (
    
    SELECT   b.BOOK_ID ,b.CATEGORY, b.AUTHOR_ID, b.PRICE, a.AUTHOR_NAME
    FROM BOOK b JOIN AUTHOR a
    ON b.AUTHOR_ID = a.AUTHOR_ID

), 

TLE2 as (
    
    SELECT BOOK_ID ,SUM(SALES) as SALES FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID

),

TLE3 as (

-- 코드를 입력하세요
    SELECT b.AUTHOR_ID,b.AUTHOR_NAME,b.CATEGORY ,(bs.SALES)*(b.PRICE) as SALES
    FROM TLE b JOIN TLE2 bs
    ON b.BOOK_ID = bs.BOOK_ID

)


SELECT AUTHOR_ID,AUTHOR_NAME,CATEGORY ,SUM(TLE3.SALES) as TOTAL_SALES
FROM TLE3
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY AUTHOR_ID ASC ,CATEGORY DESC