SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI 
INNER JOIN ANIMAL_OUTS AO USING (ANIMAL_ID)
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%'
AND AO.SEX_UPON_OUTCOME REGEXP '^(Spayed|Neutered)'
ORDER BY AI.ANIMAL_ID;
