WITH TLE AS(

    SELECT DEPT_ID ,ROUND(AVG(SAL),0) as AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT h.DEPT_ID , h.DEPT_NAME_EN , t.AVG_SAL
FROM HR_DEPARTMENT h JOIN TLE t
ON h.DEPT_ID = t.DEPT_ID
ORDER BY t.AVG_SAL DESC;